[package]
name = "atlas-testnet-hieuwb"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[features]
default = []

[dependencies]
solana-program = "2.1.5"

[dev-dependencies]
solana-program-test = "2.1.5"
solana-sdk = "2.1.5"
